name: Greetings

on: [pull_request_target, issues]

permissions:
  pull-requests: write
  issues: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7 # v1
        continue-on-error: true
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}
          issue-message: "Thanks for reporting this issue, don't forget to star this project if you haven't already to help us reach a wider audience."
          pr-message: "Thanks for implementing a fix, could you ensure that the test covers your changes if applicable."
